1 задача
js-tasks-ru/jsbasic-20240520_natalushka94 pull request #1
Opened 2024-05-22 13:58 UTC by natty-dv

Функция, суммирующая 2 числа

2024-05-22 13:58 UTC, jsru-1 commented
Спасибо за отправленный пулриквест, теперь @SinimaWath должен запустить тесты.

2024-05-22 14:26 UTC, SinimaWath requested changes

2024-05-22 14:26 UTC, SinimaWath commented on 0-module/1-task/index.js
> +  console.log(m + n);
Давай уберем лишний console.log, для решенной задачи он не нужен

2024-05-22 14:26 UTC, SinimaWath commented on 0-module/1-task/index.js
> +sum(1, 1);
Давай уберем этот вызов, в файле с задачей должно быть только решение задачи

2024-05-24 18:12 UTC, SinimaWath approved these changes

2024-05-24 18:12 UTC, merged